### ISSUE TITLE
Auth error when logging in w/ non-UW google account

### ISSUE THREAD

**Issue by vinh-hua** [autumn-info-442a/team-e#6]

**Comment by vinh-hua** [comment]
Got an authorization error when logging into google w/ non-UW account

**Comment by hyperion32** [comment]
Not sure if we can change the type of error the occurs when logging in with a non UW account. We can put this on the backburner for now

**Comment by hyperion32** [comment]
Add log in with UW Gmail to make it more clear

**Comment by cahillaw** [comment]
now says Log In With UW Gmail, kinda unaesthetic but it is more clear.
